dds_domain_id: 1  # Domain id
network_interface: "lo" # Interface
is_simulation: True # Simulation mode

hid_settings:
  keyboard:
    enable: True
    device_name: "/dev/input/event3"
    keyboard_mappings:
      passive_mode: "F1"
      fixed_stand_mode: "F2"
      swing_test_mode: "F3"
      free_stand_mode: "F4"
      trotting_mode: "F5"
      move_base_mode: "F6"
  joystick:
    enable: False
    device_name: "/dev/input/event22"
    joystick_mappings:
      forward: 1
      backward: 2
      left: 3
      right: 4
      up: 5
      down: 6
      roll_left: 7
      roll_right: 8
      pitch_up: 9
      pitch_down: 10
      yaw_left: 11
      yaw_right: 12

control_settings:
  gain_sets:
    zero_gain_set:
      joint0: { kp: 0.0, kd: 0.0 }
      joint1: { kp: 0.0, kd: 0.0 }
      joint2: { kp: 0.0, kd: 0.0 }
      joint3: { kp: 0.0, kd: 0.0 }
      joint4: { kp: 0.0, kd: 0.0 }
      joint5: { kp: 0.0, kd: 0.0 }
      joint6: { kp: 0.0, kd: 0.0 }
      joint7: { kp: 0.0, kd: 0.0 }
      joint8: { kp: 0.0, kd: 0.0 }
      joint9: { kp: 0.0, kd: 0.0 }
      joint10: { kp: 0.0, kd: 0.0 }
      joint11: { kp: 0.0, kd: 0.0 }
    passive_gain_set:
      joint0: { kp: 0.0, kd: 8.0 }
      joint1: { kp: 0.0, kd: 8.0 }
      joint2: { kp: 0.0, kd: 8.0 }
      joint3: { kp: 0.0, kd: 8.0 }
      joint4: { kp: 0.0, kd: 8.0 }
      joint5: { kp: 0.0, kd: 8.0 }
      joint6: { kp: 0.0, kd: 8.0 }
      joint7: { kp: 0.0, kd: 8.0 }
      joint8: { kp: 0.0, kd: 8.0 }
      joint9: { kp: 0.0, kd: 8.0 }
      joint10: { kp: 0.0, kd: 8.0 }
      joint11: { kp: 0.0, kd: 8.0 }
    stance_gain_set:
      joint0: { kp: 80.0, kd: 3.5 }
      joint1: { kp: 80.0, kd: 3.5 }
      joint2: { kp: 80.0, kd: 3.5 }
      joint3: { kp: 80.0, kd: 3.5 }
      joint4: { kp: 80.0, kd: 3.5 }
      joint5: { kp: 80.0, kd: 3.5 }
      joint6: { kp: 80.0, kd: 3.5 }
      joint7: { kp: 80.0, kd: 3.5 }
      joint8: { kp: 80.0, kd: 3.5 }
      joint9: { kp: 80.0, kd: 3.5 }
      joint10: { kp: 80.0, kd: 3.5 }
      joint11: { kp: 80.0, kd: 3.5 }
    lying_gain_set:
      joint0: { kp: 50.0, kd: 3.5 }
      joint1: { kp: 50.0, kd: 3.5 }
      joint2: { kp: 50.0, kd: 3.5 }
      joint3: { kp: 50.0, kd: 3.5 }
      joint4: { kp: 50.0, kd: 3.5 }
      joint5: { kp: 50.0, kd: 3.5 }
      joint6: { kp: 50.0, kd: 3.5 }
      joint7: { kp: 50.0, kd: 3.5 }
      joint8: { kp: 50.0, kd: 3.5 }
      joint9: { kp: 50.0, kd: 3.5 }
      joint10: { kp: 50.0, kd: 3.5 }
      joint11: { kp: 50.0, kd: 3.5 }
  passive_mode:
    default_joint_gains: 'passive_gain_set'
  fixed_stand_mode:
    default_joint_gains: 'stance_gain_set'
    q_desired: [ 0.00571868, 0.608813, -1.21763, -0.00571868, 0.608813, -1.21763,
                 0.00571868, 0.608813, -1.21763, -0.00571868, 0.608813, -1.21763 ]
    duration_ms: 1200
  lying_down_mode:
    default_joint_gains: 'lying_gain_set'
    q_desired: [ 0.0473455, 1.22187, -2.44375, -0.0473455, 1.22187, -2.44375,
                 0.0473455, 1.22187, -2.44375, -0.0473455, 1.22187, -2.44375 ]
    duration_ms: 1200
  swing_test_mode:
    default_joint_gains: 'stance_gain_set'