dds_domain_id: 1  # Domain id
network_interface: "lo" # Interface
is_simulation: True # Simulation mode

hid_config:
  keyboard:
    enable: True
    device_name: "/dev/input/event3"
    keyboard_mappings:
      passive_mode: "F1"
      fixed_stand_mode: "F2"
      free_stand_mode: "F3"
      trotting_mode: "F4"
      move_base_mode: "F5"
  joystick:
    enable: False
    device_name: "/dev/input/event22"
    joystick_mappings:
      forward: 1
      backward: 2
      left: 3
      right: 4
      up: 5
      down: 6
      roll_left: 7
      roll_right: 8
      pitch_up: 9
      pitch_down: 10
      yaw_left: 11
      yaw_right: 12


